CFG.maskSlots = {
	legacy = 'Старый',
	hat = 'Голова',
	eyes = 'Глаза',
	ears = 'Уши',
	mouth = 'Рот',
	neck = 'Шея',
}

CFG.masks = {
	cleaver = {
		name = L.mask_cleaver,
		mdl = 'models/props_lab/Cleaver.mdl',
		pos = Vector(-3.1, 6.7, 5.2),
		ang = Angle(0, 85, 0),
		scale = 0.6,
		slots = {
			'hat',
		},
	},
	monkey = {
		name = L.mask_monkey,
		mdl = 'models/sal/halloween/monkey.mdl',
		pos = Vector(-4.1, 0, -2.2),
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	zombie = {
		name = L.mask_zombie,
		mdl = 'models/sal/halloween/zombie.mdl',
		pos = Vector(-3.7, 0, -2),
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	hockey = {
		name = L.mask_hockey,
		mdl = 'models/sal/acc/fix/mask_2.mdl',
		pos = Vector(-4, 0, -1.9),
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	gingerbread = {
		name = L.mask_gingerbread,
		mdl = 'models/sal/gingerbread.mdl',
		pos = Vector(-4.2, 0, -2),
		ang = Angle(-2.8, 0, 0),
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
    barsetka = {
		name = 'Барсетка',
		mdl = 'models/octoteam/halloween/moth_bag.mdl',
        desc = 'Теперь ты опастный тип',
        icon = 'octoteam/icons/clothes_tie.png',
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	pumpkin = {
		name = L.mask_pumpkin,
		mdl = 'models/halloween2015/pumbkin_n_f01.mdl',
		pos = Vector(-2.9, 0, 0.7),
		ang = Angle(11, 0, 0),
		scale = 0.4,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	top_hat = {
		name = L.mask_top_hat,
		mdl = 'models/player/items/humans/top_hat.mdl',
		pos = Vector(-3.1, 0, -3.6),
		slots = {
			'hat',
		},
	},
	doctor = {
		name = L.mask_doctor,
		mdl = 'models/sal/halloween/doctor.mdl',
		pos = Vector(-5, 0, -2),
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	pig = {
		name = L.mask_pig,
		mdl = 'models/sal/pig.mdl',
		pos = Vector(-4.2, 0, -2.4),
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	bear = {
		name = L.mask_bear,
		mdl = 'models/sal/bear.mdl',
		pos = Vector(-4.3, 0, -1.7),
		ang = Angle(-5.6, 0, 0),
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	turtle = {
		name = L.mask_turtle,
		mdl = 'models/props/de_tides/vending_turtle.mdl',
		pos = Vector(-3.2, 0.1, 3.8),
		ang = Angle(-1.3, -95.9, -3.8),
		scale = 0.61,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	deer = {
		name = L.mask_deer,
		mdl = 'models/monstermash/gibs/head_deerhaunter.mdl',
		pos = Vector(-5.1, 0, -6.6),
		ang = Angle(-3.4, 1.5, -2.9),
		scale = 1.3,
		skin = 1,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	mummy = {
		name = L.mask_mummy,
		mdl = 'models/monstermash/gibs/head_mummy.mdl',
		pos = Vector(0, 0, -7),
		ang = Angle(0, 95.1, -18.6),
		scale = 1.02,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	santa = {
		name = 'Новогодний колпак',
		icon = 'octoteam/icons/xmas_hat.png',
		mdl = 'models/cloud/kn_santahat.mdl',
		pos = Vector(-4.6, 0, -3.8),
		ang = Angle(0.8, -85.2, 81.1),
		scale = 1.02,
		slots = {
			'hat',
		},
	},
	gasmask = {
		name = L.mask_gasmask,
		icon = 'octoteam/icons/gasmask.png',
		desc = L.desc_gasmask,
		mdl = 'models/splinks/kf2/cosmetics/gas_mask.mdl',
		pos = Vector(-4.4, 0, -2.7),
		ang = Angle(0, 0, 0),
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},

	cap_dobrograd = {
		name = L.cap_dobrograd,
		icon = 'octoteam/icons/clothes_cap.png',
		desc = L.cap_dobrograd_desc,
		persistent = true,
		mdl = 'models/modified/hat08.mdl',
		mat = 'sal/hats/hat08_patriot',
		pos = Vector(-3.7, 0, 1.1),
		skin = 1,
        price = 500,
		slots = {
			'hat',
		},
	},
	orangecap = {
		name = 'Оранжевая кепка',
		icon = 'octoteam/icons/clothes_cap.png',
		desc = 'Обычная оранжевая кепка с каким-то логотипом',
		mdl = 'models/modified/hat08.mdl',
		pos = Vector(-3.7, 0, 1.1),
		skin = 0,
		price = 500,
		slots = {
			'hat',
		},
	},
	redcap = {
		name = 'Красная кепка',
		icon = 'octoteam/icons/clothes_cap.png',
		desc = 'Классическая красная кепка с каким-то логотипом',
		mdl = 'models/modified/hat08.mdl',
		pos = Vector(-3.7, 0, 1.1),
		skin = 4,
		price = 400,
		slots = {
			'hat',
		},
	},
	cap_meteorite = {
		name = 'Кепка "Meteorite"',
		icon = 'octoteam/icons/clothes_cap.png',
		desc = 'Классическая кепка черного цвета с логотипом "Meteorite"',
		mdl = 'models/modified/hat08.mdl',
		pos = Vector(-3.7, 0, 1.1),
		skin = 8,
		price = 500,
		slots = {
			'hat',
		},
	},
	cap_monkey = {
		name = 'Кепка "Orang-O-Tang"',
		icon = 'octoteam/icons/clothes_cap.png',
		desc = 'Классическая кепка коричневого цвета с логотипом "Orang-O-Tang" и обезьянкой',
		mdl = 'models/modified/hat08.mdl',
		pos = Vector(-3.7, 0, 1.1),
		skin = 11,
		price = 500,
		slots = {
			'hat',
		},
	},
	cap_quests = {
		name = 'Кепка "Лига Квестов"',
		icon = 'octoteam/icons/clothes_cap.png',
		desc = 'Фирменная кепка Лиги Квестов',
		mdl = 'models/leeetov/quest_cap.mdl',
		pos = Vector(-3.6, -0.19, 1.8),
		slots = {
        price = 500,   
			'hat',
		},
	},

	mask_hoffman = {
		name = 'Маска с эмблемой короны',
		desc = L.mask_hoffman,
		persistent = true,
		mdl = 'models/sal/acc/fix/mask_2.mdl',
		pos = Vector(-3.8, 0, -1.9),
		ang = Angle(0, 0, 0),
		skin = 5,
        price = 5000,
		persistent = true,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	hoff_widesmile = {
		name = 'Пакет на голову',
		desc = '"Звериный скал"',
		persistent = true,
		mdl = 'models/sal/halloween/bag.mdl',
		pos = Vector(-3.3, 0, -1.5),
		ang = Angle(0, 0, 0),
		skin = 1,
        price = 1200,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	hoff_tears = {
		name = 'Пакет на голову',
		desc = '"Плак-плак"',
		persistent = true,
		mdl = 'models/sal/halloween/bag.mdl',
		pos = Vector(-3.3, 0, -1.5),
		ang = Angle(0, 0, 0),
		skin = 2,
        price = 1200,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	hoff_tinysmile = {
		name = 'Пакет на голову',
		desc = '"Легкий скал"',
		persistent = true,
		mdl = 'models/sal/halloween/bag.mdl',
		pos = Vector(-3.3, 0, -1.5),
		ang = Angle(0, 0, 0),
		skin = 3,
        price = 1200,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	hoff_dude = {
		name = 'Пакет на голову',
		desc = '"Чувак"',
		persistent = true,
		mdl = 'models/sal/halloween/bag.mdl',
		pos = Vector(-3.3, 0, -1.5),
		ang = Angle(0, 0, 0),
		skin = 5,
        price = 1200,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	hoff_killme = {
		name = 'Пакет на голову',
		desc = '"Пожалуйста, убейте"',
		persistent = true,
		mdl = 'models/sal/halloween/bag.mdl',
		pos = Vector(-3.3, 0, -1.5),
		ang = Angle(0, 0, 0),
		skin = 8,
        price = 1200,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	hoff_helpme = {
		name = 'Пакет на голову',
		desc = '"Помогите"',
		persistent = true,
		mdl = 'models/sal/halloween/bag.mdl',
		pos = Vector(-3.3, 0, -1.5),
		ang = Angle(0, 0, 0),
		skin = 18,
        price = 1200,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	hardhat = {
		name = 'Строительная каска',
		persistent = true,
		mdl = 'models/props_junk/hardhat.mdl',
		pos = Vector(-3.5, 0, 1.2),
		ang = Angle(-5, 0, 0),
		scale = 0.73,
        price = 300,
		slots = {
			'hat',
		},
	},
	peakless = {
		name = 'Бескозырка',
		desc = 'Удобная бескозырка, только без острия',
		icon = 'octoteam/icons/peaky_hat.png',
		mdl = 'models/modified/hat06.mdl',
		pos = Vector(-4.5, -0.2, 2.2),
		ang = Angle(0, 4.1, 0),
		scale = 1.01,
		price = 1200,
		slots = {
			'hat',
		},
	},
	ninja = {
		name = 'Балаклава',
		desc = 'Маска, закрывающая не только лицо, но и часть головы и шею',
		icon = 'octoteam/icons/robber.png',
		mdl = 'models/sal/halloween/ninja.mdl',
		pos = Vector(-4.2, 0.21, -2),
		scale = 1.042,
        price = 400,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	balaclava = {
		name = 'Черная балаклава',
		desc = 'Маска, закрывающая не только лицо, но и часть головы и шею',
		icon = 'octoteam/icons/robber.png',
		mdl = 'models/modified/balaclava.mdl',
		pos = Vector(-3.8, 0.0, 1),
		price = 500,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	balaclava_g = {
		name = 'Зеленая балаклава',
		desc = 'Маска, закрывающая не только лицо, но и часть головы и шею',
		icon = 'octoteam/icons/robber.png',
		mdl = 'models/modified/balaclava_g.mdl',
		pos = Vector(-2.3, 0.0, 2.2),
		price = 500,
		hideName = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},

	baseball = {
		name = 'Классическая бейсболка',
		desc = 'Бейсболка с логотипом лиги бейсбола',
		icon = 'octoteam/icons/clothes_cap.png',
		mdl = 'models/modified/hat07.mdl',
		pos = Vector(-4, -0.19, 1.8),
		ang = Angle(-7.2, 0, 0),
		skin = 10,
		price = 500,
		slots = {
			'hat',
		},
	},
	baseball_jordan = {
		name = 'Бейсболка Jordan',
		desc = 'Черная бейсболка с характерной баскетбольной символикой',
		icon = 'octoteam/icons/clothes_cap.png',
		mdl = 'models/modified/hat07.mdl',
		pos = Vector(-4, -0.19, 1.8),
		ang = Angle(-7.2, 0, 0),
		skin = 0,
		price = 500,
		slots = {
			'hat',
		},
	},
	yellowbaseball = {
		name = 'Желтая бейсболка',
		desc = 'Бейсболка желтого цвета с вышитой надписью',
		icon = 'octoteam/icons/clothes_cap.png',
		mdl = 'models/modified/hat07.mdl',
		pos = Vector(-4, -0.19, 1.8),
		ang = Angle(-7.2, 0, 0),
		skin = 1,
		price = 500,
		slots = {
			'hat',
		},
	},
	baseball_stetson = {
		name = 'Бейсболка Stetson',
		desc = 'Бейсболка в классическом американском стиле',
		icon = 'octoteam/icons/clothes_cap.png',
		mdl = 'models/modified/hat07.mdl',
		pos = Vector(-4, -0.19, 1.8),
		ang = Angle(-7.2, 0, 0),
		skin = 3,
		price = 500,
		slots = {
			'hat',
		},
	},
	baseball_detroit = {
		name = 'Бейсболка Detroit',
		desc = 'Классическая бейсболка темно-синего цвета с вышитым на передней части логотипом города',
		icon = 'octoteam/icons/clothes_cap.png',
		mdl = 'models/modified/hat07.mdl',
		pos = Vector(-4, -0.19, 1.8),
		ang = Angle(-7.2, 0, 0),
		skin = 6,
		price = 500,
		slots = {
			'hat',
		},
	},

	bandana = {
		name = 'Черная бандана',
		desc = 'Небольшой кусок ткани, служащий для сокрытия лица',
		icon = 'octoteam/icons/bandana.png',
		mdl = 'models/octoteam/accessory/bandana.mdl',
		pos = Vector(-3.95, 0.1, -4),
		ang = Angle(0.2, 0, 0),
		scale = 1.03,
		skin = 5,
		price = 500,
		hideName = true,
		slots = {
			'mouth',
		},
	},
	redbandana = {
		name = 'Красная бандана',
		desc = 'Небольшой кусок ткани, служащий для сокрытия лица',
		icon = 'octoteam/icons/bandana.png',
		mdl = 'models/octoteam/accessory/bandana.mdl',
		pos = Vector(-3.95, 0.1, -4),
		ang = Angle(0.2, 0, 0),
		scale = 1.03,
		skin = 1,
		price = 500,
		hideName = true,
		slots = {
			'mouth',
		},
	},
	yellowbandana = {
		name = 'Желтая бандана',
		desc = 'Небольшой кусок ткани, служащий для сокрытия лица',
		icon = 'octoteam/icons/bandana.png',
		mdl = 'models/octoteam/accessory/bandana.mdl',
		pos = Vector(-3.95, 0.1, -4),
		ang = Angle(0.2, 0, 0),
		scale = 1.03,
		skin = 2,
		price = 500,
		hideName = true,
		slots = {
			'mouth',
		},
	},
	greenbandana = {
		name = 'Зеленая бандана',
		desc = 'Небольшой кусок ткани, служащий для сокрытия лица',
		icon = 'octoteam/icons/bandana.png',
		mdl = 'models/octoteam/accessory/bandana.mdl',
		pos = Vector(-3.95, 0.1, -4),
		ang = Angle(0.2, 0, 0),
		scale = 1.03,
		skin = 3,
		price = 500,
		hideName = true,
		slots = {
			'mouth',
		},
	},
	bluebandana = {
		name = 'Синяя бандана',
		desc = 'Небольшой кусок ткани, служащий для сокрытия лица',
		icon = 'octoteam/icons/bandana.png',
		mdl = 'models/octoteam/accessory/bandana.mdl',
		pos = Vector(-3.95, 0.1, -4),
		ang = Angle(0.2, 0, 0),
		scale = 1.03,
		skin = 4,
		price = 500,
		hideName = true,
		slots = {
			'mouth',
		},
	},
	medical_mask = {
		name = 'Медицинская маска',
		desc = 'Сейчас это актуально как никогда',
		mdl = 'models/dean/gtaiv/mask.mdl',
		pos = Vector(-3.5, 0, -3.1),
		ang = Angle(11.2, 0, 0),
		scale = 1.01,
		hideName = true,
		slots = {
			'mouth',
		},
	},

	blackglasses = {
		name = 'Черные очки',
		desc = 'Самые стандартные очки с дешевой черной оправой',
		icon = 'octoteam/icons/glasses_classic.png',
		mdl = 'models/modified/glasses02.mdl',
		pos = Vector(-3.9, 0, -0.13),
		skin = 3,
		price = 700,
		slots = {
			'eyes',
		},
	},
	glasses = {
		name = 'Классические очки',
		desc = 'Самые стандартные очки с дешевой оправой',
		icon = 'octoteam/icons/glasses_classic.png',
		mdl = 'models/modified/glasses02.mdl',
		pos = Vector(-3.9, 0, -0.13),
		skin = 0,
		price = 700,
		slots = {
			'eyes',
		},
	},
	redglasses = {
		name = 'Красные очки',
		desc = 'Самые стандартные очки с дешевой красной оправой',
		icon = 'octoteam/icons/glasses_classic.png',
		mdl = 'models/modified/glasses02.mdl',
		pos = Vector(-3.9, 0, -0.13),
		skin = 1,
		price = 700,
		slots = {
			'eyes',
		},
	},
	whiteglasses = {
		name = 'Белые очки',
		desc = 'Самые стандартные очки с дешевой белой оправой',
		icon = 'octoteam/icons/glasses_classic.png',
		mdl = 'models/modified/glasses02.mdl',
		pos = Vector(-3.9, 0, -0.13),
		skin = 2,
		price = 700,
		slots = {
			'eyes',
		},
	},
	brownglasses = {
		name = 'Коричневые очки',
		desc = 'Самые стандартные очки с дешевой коричневой оправой',
		icon = 'octoteam/icons/glasses_classic.png',
		mdl = 'models/modified/glasses02.mdl',
		pos = Vector(-3.9, 0, -0.13),
		skin = 4,
		price = 700,
		slots = {
			'eyes',
		},
	},

	modelli = {
		name = 'Очки LQB "Modelli"',
		desc = 'Фирменные очки LQB, позолоченные дужки которых выполнены в виде специального узора',
		icon = 'octoteam/icons/sun_glasses.png',
		mdl = 'models/modified/lqb_glass2.mdl',
		pos = Vector(-3.9, 0, -0.13),
        price = 900,
		slots = {
			'eyes',
		},
	},
	rettelinee = {
		name = 'Очки Gucci "Rette Linee"',
		desc = 'Очки Gucci с фирменным узором на дужках',
		icon = 'octoteam/icons/glasses_aviator.png',
		mdl = 'models/modified/lqb_glass1.mdl',
		pos = Vector(-3.9, 0, -0.13),
        price = 900,
		slots = {
			'eyes',
		},
	},

	aviator = {
		name = 'Черные авиаторы',
		desc = 'Стильные очки "капельки" черного цвета, имеющие достаточно удобную форму оправы и линз',
		icon = 'octoteam/icons/glasses_aviator.png',
		mdl = 'models/modified/glasses01.mdl',
		pos = Vector(-4.35, 0, -0.1),
		skin = 0,
		price = 1200,
		slots = {
			'eyes',
		},
	},
	greenaviator = {
		name = 'Зеленые авиаторы',
		desc = 'Стильные очки "капельки" зеленого цвета, имеющие достаточно удобную форму оправы и линз',
		icon = 'octoteam/icons/glasses_aviator.png',
		mdl = 'models/modified/glasses01.mdl',
		pos = Vector(-4.35, 0, -0.1),
		skin = 2,
		price = 1200,
		slots = {
			'eyes',
		},
	},
	brownaviator = {
		name = 'Коричневые авиаторы',
		desc = 'Стильные очки "капельки" коричневого цвета, имеющие достаточно удобную форму оправы и линз',
		icon = 'octoteam/icons/glasses_aviator.png',
		mdl = 'models/modified/glasses01.mdl',
		pos = Vector(-4.35, 0, -0.1),
		skin = 3,
		price = 1200,
		slots = {
			'eyes',
		},
	},
	orangeaviator = {
		name = 'Оранжевые авиаторы',
		desc = 'Стильные очки "капельки" оранжевого цвета, имеющие достаточно удобную форму оправы и линз',
		icon = 'octoteam/icons/glasses_aviator.png',
		mdl = 'models/modified/glasses01.mdl',
		pos = Vector(-4.35, 0, -0.1),
		skin = 4,
		price = 1200,
		slots = {
			'eyes',
		},
	},
	greyaviator = {
		name = 'Серые авиаторы',
		desc = 'Стильные очки "капельки" серого цвета, имеющие достаточно удобную форму оправы и линз',
		icon = 'octoteam/icons/glasses_aviator.png',
		mdl = 'models/modified/glasses01.mdl',
		pos = Vector(-4.35, 0, -0.1),
		skin = 5,
		price = 1200,
		slots = {
			'eyes',
		},
	},
	greyfedora = {
		name = 'Серая федора',
		desc = 'Легкая шляпка серого цвета, обвитая лентой',
		icon = 'octoteam/icons/detective_hat.png',
		mdl = 'models/modified/hat01_fix.mdl',
		pos = Vector(-4.1, 0, 1.8),
		ang = Angle(0, 0, 0),
		scale = 0.96,
		skin = 0,
		price = 1500,
		slots = {
			'hat',
		},
	},
	fedora = {
		name = 'Черная федора',
		desc = 'Легкая шляпка черного цвета, обвитая лентой',
		icon = 'octoteam/icons/detective_hat.png',
		mdl = 'models/modified/hat01_fix.mdl',
		pos = Vector(-4.1, 0, 1.8),
		ang = Angle(0, 0, 0),
		scale = 0.96,
		skin = 1,
		price = 1500,
		slots = {
			'hat',
		},
	},
	whitefedora = {
		name = 'Белая федора',
		desc = 'Легкая шляпка белого цвета, обвитая лентой',
		icon = 'octoteam/icons/detective_hat.png',
		mdl = 'models/modified/hat01_fix.mdl',
		pos = Vector(-4.1, 0, 1.8),
		ang = Angle(0, 0, 0),
		scale = 0.96,
		skin = 2,
		price = 1500,
		slots = {
			'hat',
		},
	},
	beigefedora = {
		name = 'Бежевая федора',
		desc = 'Легкая шляпка бежевого цвета, обвитая лентой',
		icon = 'octoteam/icons/detective_hat.png',
		mdl = 'models/modified/hat01_fix.mdl',
		pos = Vector(-4.1, 0, 1.8),
		ang = Angle(0, 0, 0),
		scale = 0.96,
		skin = 3,
		price = 1500,
		slots = {
			'hat',
		},
	},
	smartglasses = {
		name = 'R&C SmartGlasses',
		desc = 'Умные очки от компании R&C, выполненные из алюминия черного цвета. На боковой панельке очков есть сенсорная панель управления. На правой линзе выведено изображение с доступом к приложениям',
		icon = octolib.icons.color('rc_glasses'),
		mdl = 'models/rnc/acessories/rnc_smart_glasses01.mdl',
		pos = Vector(-2.6, 0.1, -0.2),
		ang = Angle(0, 0, 0),
        price = 2500,
		scale = 0.92,
		slots = {
			'eyes',
		},
	},
	brown_hat = {
		name = 'Коричневая шляпа',
		desc = 'Уникальная шляпа, как у известного маньяка. Жуткая штука, которая дополнит не только Хэллоуинский образ, но и любой другой повседневный',
		icon = octolib.icons.color('detective_hat'),
		mdl = 'models/octoteam/freddy/krueger_hat.mdl',
		pos = Vector(-1.5, -0.1, -67.0),
		ang = Angle(-2, 0, 0),
        price = 1900,
		persistent = true,
		slots = {
			'hat',
		},
	},
	potter_glasses = {
		name = 'Круглые очки',
		desc = 'Круглые очки, которые помогут дополнить любой образ',
		icon = octolib.icons.color('glasses_classic'),
		mdl = 'models/octoteam/glasses_potter/glasses_poter.mdl',
		pos = Vector(-3.9, -0.2, -70.9),
		ang = Angle(0, 0, 0),
		scale = 1.05,
        price = 900,
		persistent = true,
		slots = {
			'eyes',
		},
	},

	-- winter 2023
	ushanka = {
		name = 'Шапка-ушанка',
		desc = 'Настоящий дух отсталый зимы Спасает от холода',
		icon = octolib.icons.color('clothes_ushanka'),
		mdl = 'models/octoteam/xmas/shapka_ushanka.mdl',
		pos = Vector(-4.3, 0.1, -67.0),
		ang = Angle(0, 0, 0),
		scale = 1.0,
        price = 2000,
		warm = true,
		persistent = true,
		slots = {
			'hat',
		},
	},
    shapka = {
		name = 'Зимняя шапочка',
		desc = 'зима идет дружище!',
		icon = octolib.icons.color('clothes_ushanka'),
		mdl = 'octoteam/icons/clothes_beanie.png',
		pos = Vector(-4.3, 0.1, -67.0),
		ang = Angle(0, 0, 0),
		scale = 1.0,
        price = 3000,
		warm = true,
		persistent = true,
		slots = {
			'hat',
		},
	},
	beanie = {
		name = 'Шапка-бини',
		desc = 'Когда на районе похолодало... Спасает от холода',
		icon = octolib.icons.color('clothes_beanie'),
		mdl = 'models/modified/hat04.mdl',
		pos = Vector(-5.7, 0.0, 1.1),
		ang = Angle(-15.5, 10.5, -5.0),
		scale = 1.0,
        price = 900,
		persistent = true,
		warm = true,
		slots = {
			'hat',
		},
	},
	knitted = {
		name = 'Вязаная шапка',
		desc = 'При производстве этого продукта кто-то смог раскрыть свои чакры в состоянии глубокой медитации! Спасает от холода',
		icon = octolib.icons.color('clothes_beanie'),
		mdl = 'models/modified/hat03.mdl',
		pos = Vector(-4.2, 0.1, 1.1),
		ang = Angle(-11.0, 0.0, 0.0),
		scale = 0.99,
        price = 1200,
		persistent = true,
		warm = true,
		slots = {
			'hat',
		},
	},

	-- gentelmen donator pack
	gentlemen_hat1 = {
		name = 'Панамка',
		desc = 'Практичный головной убор для защиты от солнца',
		icon = octolib.icons.color('panama_hat'),
		mdl = 'models/octoteam/hats/panama_hat.mdl',
		pos = Vector(-10.7, 0.0, -65.4),
		ang = Angle(7.2, 0.0, 0.0),
		mass = 0.3,
		volume = 0.5,
        price = 2000,
		scale = 1.0,
		persistent = true,
		slots = {
			'hat',
		},
	},
	gentlemen_hat2 = {
		name = 'Стильная шапка',
		desc = 'Стильный головной убор для лаконичного образа',
		icon = octolib.icons.color('clothes_beanie'),
		mdl = 'models/octoteam/hats/winter_hat.mdl',
		pos = Vector(-3.9, 0.0, -69.0),
		ang = Angle(0.0, 0.0, 0.0),
		mass = 0.3,
        price = 1200,
		volume = 0.5,
		scale = 1.02,
		persistent = true,
		slots = {
			'hat',
		},
	},
	gentlemen_hat3 = {
		name = 'Коричневая шляпа',
		desc = 'Элегантный головной убор для классического образа',
		icon = octolib.icons.color('detective_hat'),
		mdl = 'models/octoteam/hats/rotang_hat.mdl',
		pos = Vector(13.2, 0.0, -66.2),
		ang = Angle(-14.5, 0.0, 0.0),
		mass = 0.3,
        price = 2000,
		volume = 0.5,
		scale = 1.0,
		persistent = true,
		slots = {
			'hat',
		},
	},
	gentlemen_glasses = {
		name = 'Спортивные очки',
		desc = 'Стильный и практичный аксессуар',
		icon = octolib.icons.color('sport_glasses'),
		mdl = 'models/octoteam/hats/jsglasses.mdl',
		pos = Vector(-4.1, 0.0, -67.5),
		ang = Angle(0.0, 0.0, 0.0),
		mass = 0.1,
        price = 1200,
		volume = 0.3,
		scale = 1.0,
        policeAllowed = true,
		persistent = true,
		slots = {
			'eyes',
		},
	},

	-- halloween 2023
	bike_helm = {
		name = 'Байкерский шлем',
		desc = 'Брутальный шлем, который дополнит любой байкерский образ',
		icon = octolib.icons.color('biker_helmet'),
		mdl = 'models/rschlw/helmet.mdl',
		pos = Vector(-4.1, 0.0, -68.1),
		ang = Angle(0.0, 0.0, 0.0),
		scale = 1.0,
        price = 1200,
		persistent = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	devil_mask = {
		name = 'Дьявольская маска',
		desc = 'Время навести ужас на улицах города!',
		icon = octolib.icons.color('devil'),
		mdl = 'models/rschlw/devil.mdl',
		pos = Vector(-4.0, 0.0, -67.3),
		ang = Angle(0.0, 0.0, 0.0),
		scale = 1.0,
        price = 1200,
		persistent = true,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},
	cowboy_hat = {
		name = 'Ковбойская шляпа',
		desc = 'Кожаная шляпа, прямо как у знаменитого бандита!',
		icon = octolib.icons.color('cowboy_hat'),
		mdl = 'models/rschlw/arthur.mdl',
		pos = Vector(-3.8, 0.0, -67.6),
		ang = Angle(0.0, 0.0, 0.0),
		scale = 1.0,
        price = 1400,
		persistent = true,
		slots = {
			'hat',
		},
	},
	respirator = {
		name = 'Респиратор',
		desc = 'Почуешь неважный запах - смело надевай!',
		icon = octolib.icons.color('respirator'),
		mdl = 'models/rschlw/resp.mdl',
		pos = Vector(-3.8, 0.0, -67.6),
		ang = Angle(0.0, 0.0, 0.0),
		scale = 1.0,
        price = 4000,
		persistent = true,
		slots = {
			'mouth',
		},
	},
	black_mask = {
		name = 'Черная маска',
		desc = 'Хороший аксессуар, чтобы скрыть свое лицо',
		mdl = 'models/rschlw/blmk.mdl',
		pos = Vector(-3.8, 0.0, -67.5),
		ang = Angle(0.0, 0.0, 0.0),
		scale = 1.0,
        price = 2500,
		slots = {
			'hat',
			'eyes',
			'mouth',
		},
	},

	-- winter 2024
	earmuffs = {
		name = 'Теплые наушники',
		desc = 'Теплый аксессуар, который согреет уши',
		icon = 'octoteam/icons/warm_headphones.png',
		mdl = 'models/accessories/airpods.mdl',
		pos = Vector(-3.6, 0.0, -74.2),
		ang = Angle(0.1, 90.0, 0.0),
		scale = 1.1,
        price = 3000,
		slots = {
			'ears',
		},
		warm = true,
	},
	scarf = {
		name = 'Шарф с узорами',
		desc = 'Теплый шарф для зимнего образа',
		icon = 'octoteam/icons/clothes_scarf.png',
		mdl = 'models/accessories/scarf_winter.mdl',
		skin = 2,
		pos = Vector(-2.9, -1.6, -14.2),
		ang = Angle(0.0, -90.0, 0.0),
		scale = 1.0,
        price = 2000,
		slots = {
			'neck',
		},
		warm = true,
		att = 'chest',
		femaleProps = {
			pos = Vector(-4.4, -1.6, -15.5),
			ang = Angle(0.0, -90.0, 0.0),
			scale = 0.96,
		},
	},
	scarf0 = {
		name = 'Светлый шарф',
		desc = 'Теплый шарф для зимнего образа',
		icon = 'octoteam/icons/clothes_scarf.png',
		mdl = 'models/accessories/scarf_winter.mdl',
		skin = 0,
		pos = Vector(-2.9, -1.6, -14.2),
		ang = Angle(0.0, -90.0, 0.0),
		scale = 1.0,
		slots = {
			'neck',
		},
		warm = true,
		att = 'chest',
		femaleProps = {
			pos = Vector(-4.4, -1.6, -15.5),
			ang = Angle(0.0, -90.0, 0.0),
			scale = 0.96,
		},
	},
	scarf1 = {
		name = 'Серый шарф',
		desc = 'Теплый шарф для зимнего образа',
		icon = 'octoteam/icons/clothes_scarf.png',
		mdl = 'models/accessories/scarf_winter.mdl',
		skin = 1,
		pos = Vector(-2.9, -1.6, -14.2),
		ang = Angle(0.0, -90.0, 0.0),
		scale = 1.0,
		slots = {
			'neck',
		},
		warm = true,
		att = 'chest',
		femaleProps = {
			pos = Vector(-4.4, -1.6, -15.5),
			ang = Angle(0.0, -90.0, 0.0),
			scale = 0.96,
		},
	},
	scarf3 = {
		name = 'Зеленый шарф',
		desc = 'Теплый шарф для зимнего образа',
		icon = 'octoteam/icons/clothes_scarf.png',
		mdl = 'models/accessories/scarf_winter.mdl',
		skin = 3,
		pos = Vector(-2.9, -1.6, -14.2),
		ang = Angle(0.0, -90.0, 0.0),
		scale = 1.0,
		slots = {
			'neck',
		},
		warm = true,
		att = 'chest',
		femaleProps = {
			pos = Vector(-4.4, -1.6, -15.5),
			ang = Angle(0.0, -90.0, 0.0),
			scale = 0.96,
		},
	},
	scarf4 = {
		name = 'Цитрусовый шарф',
		desc = 'Теплый шарф для зимнего образа',
		icon = 'octoteam/icons/clothes_scarf.png',
		mdl = 'models/accessories/scarf_winter.mdl',
		skin = 4,
		pos = Vector(-2.9, -1.6, -14.2),
		ang = Angle(0.0, -90.0, 0.0),
		scale = 1.0,
		slots = {
			'neck',
		},
		warm = true,
		att = 'chest',
		femaleProps = {
			pos = Vector(-4.4, -1.6, -15.5),
			ang = Angle(0.0, -90.0, 0.0),
			scale = 0.96,
		},
	},
	scarf5 = {
		name = 'Темный шарф',
		desc = 'Теплый шарф для зимнего образа',
		icon = 'octoteam/icons/clothes_scarf.png',
		mdl = 'models/accessories/scarf_winter.mdl',
		skin = 5,
		pos = Vector(-2.9, -1.6, -14.2),
		ang = Angle(0.0, -90.0, 0.0),
		scale = 1.0,
		slots = {
			'neck',
		},
		warm = true,
		att = 'chest',
		femaleProps = {
			pos = Vector(-4.4, -1.6, -15.5),
			ang = Angle(0.0, -90.0, 0.0),
			scale = 0.96,
		},
	},
	scarf6 = {
		name = 'Красный шарф',
		desc = 'Теплый шарф для зимнего образа',
		icon = 'octoteam/icons/clothes_scarf.png',
		mdl = 'models/accessories/scarf_winter.mdl',
		skin = 6,
		pos = Vector(-2.9, -1.6, -14.2),
		ang = Angle(0.0, -90.0, 0.0),
		scale = 1.0,
		slots = {
			'neck',
		},
		warm = true,
		att = 'chest',
		femaleProps = {
			pos = Vector(-4.4, -1.6, -15.5),
			ang = Angle(0.0, -90.0, 0.0),
			scale = 0.96,
		},
	},
	hat_pompon4 = {
		name = 'Шапка с помпоном',
		desc = 'Зеленая теплая шапка с помпоном',
		icon = 'octoteam/icons/clothes_beanie.png',
		mdl = 'models/accessories/w_hat.mdl',
		skin = 4,
		pos = Vector(-4.0, 0.0, -22.3),
		ang = Angle(0.0, 180.0, 0.0),
		scale = 1.1,
		slots = {
			'hat',
		},
		warm = true,
	},
	hat_pompon1 = {
		name = 'Шапка с помпоном',
		desc = 'Белая теплая шапка с помпоном',
		icon = 'octoteam/icons/clothes_beanie.png',
		mdl = 'models/accessories/w_hat.mdl',
		skin = 1,
		pos = Vector(-4.0, 0.0, -22.3),
		ang = Angle(0.0, 180.0, 0.0),
		scale = 1.1,
        price = 2000,
		slots = {
			'hat',
		},
		warm = true,
	},
	hat_pompon = {
		name = 'Шапка с помпоном',
		desc = 'Синяя теплая шапка с помпоном',
		icon = 'octoteam/icons/clothes_beanie.png',
		mdl = 'models/accessories/w_hat.mdl',
		skin = 0,
		pos = Vector(-4.0, 0.0, -22.3),
		ang = Angle(0.0, 180.0, 0.0),
		scale = 1.1,
		slots = {
			'hat',
		},
		warm = true,
	},
	hat_pompon2 = {
		name = 'Шапка с помпоном',
		desc = 'Розовая теплая шапка с помпоном',
		icon = 'octoteam/icons/clothes_beanie.png',
		mdl = 'models/accessories/w_hat.mdl',
		skin = 2,
		pos = Vector(-4.0, 0.0, -22.3),
		ang = Angle(0.0, 180.0, 0.0),
		scale = 1.1,
		slots = {
			'hat',
		},
		warm = true,
	},
	hat_pompon3 = {
		name = 'Шапка с помпоном',
		desc = 'Красная теплая шапка с помпоном',
		icon = 'octoteam/icons/clothes_beanie.png',
		mdl = 'models/accessories/w_hat.mdl',
		skin = 3,
		pos = Vector(-4.0, 0.0, -22.3),
		ang = Angle(0.0, 180.0, 0.0),
		scale = 1.1,
		slots = {
			'hat',
		},
		warm = true,
	},
	hat_docker = {
		name = 'Шапка докер',
		desc = 'Теплая шапка без козырька',
		icon = 'octoteam/icons/docker_hat.png',
		mdl = 'models/accessories/hat_2.mdl',
		pos = Vector(-4.2, 5.3, -51.2),
		ang = Angle(0.0, 0.0, 0.0),
		scale = 1.03,
		slots = {
			'hat',
		},
		warm = true,
	},
	snowboard_goggles = {
		name = 'Очки для сноуборда',
		desc = 'Очень полезный аксессуар для спортсменов',
		icon = 'octoteam/icons/ski_goggles.png',
		mdl = 'models/accessories/googles.mdl',
		pos = Vector(1.9, 0.0, 0.3),
		ang = Angle(0.0, -90.0, 0.0),
		scale = 1.02,
		slots = {
			'hat',
			'eyes',
		},
		warm = true,
	},
	gatsby_cap = {
		name = 'Восьмиклинка',
		desc = 'Теплая шапка для стильных мужчин',
		icon = 'octoteam/icons/clothes_beanie.png',
		mdl = 'models/accessories/hat.mdl',
		pos = Vector(-4.1, 5.7, -50.4),
		ang = Angle(0.0, 0.0, 0.0),
		scale = 1.03,
		slots = {
			'hat',
		},
		warm = true,
	},
	fur_hat = {
		name = 'Меховая шапка',
		desc = 'Очень теплая меховая шапка',
		icon = 'octoteam/icons/clothes_beanie.png',
		mdl = 'models/accessories/t_hat.mdl',
		pos = Vector(-3.1, -0.1, -67.8),
		ang = Angle(0.0, -90.0, 0.0),
		scale = 1,
		slots = {
			'hat',
		},
		warm = true,
	},
	hat_lens = {
		name = 'Шапка с линзами',
		desc = 'Модный аксессуар на зиму!',
		icon = 'octoteam/icons/clothes_beanie.png',
		mdl = 'models/accessories/hat_lens.mdl',
		pos = Vector(-3.7, 1.2, -12.9),
		ang = Angle(0.0, -90.0, 0.0),
		scale = 1,
        price = 1200,
		slots = {
			'hat',
		},
		warm = true,
	},
}