
// DO NOT EDIT THIS FILE!
// LOOK IN THE mlogs/lua/mLog/config folder to edit the config!

mLog = {}
mLog.root = "mLog/"
mLog.prefix = "mLog"
mLog.config = {}
mLog.Logger = http
mLog.version = "1.1.3"
function mLog.Print(str)
	if SERVER or CLIENT then
		if type(str) != "table" then
			MsgC(Color(255,100,0), "[".. mLog.prefix .."] ", color_white, tostring(str) .. "\n")
		else
			for k,v in ipairs(str) do
				MsgC(Color(255,100,0), "[".. mLog.prefix .."] ", color_white, tostring(k).."\t"..tostring(v) .. "\n")
			end
		end
	end 
end

if CLIENT then
	function mLog.ChatPrint(str)
		if type(str) != "table" then
			chat.AddText(Color(255,100,0), "[".. mLog.prefix .."] ", color_white, tostring(str))
			if ValidPanel(mLog.Panel) then
				mLog.Panel.PopupText = tostring(str)
			end
		else
			for k,v in ipairs(str) do
				chat.AddText(Color(255,100,0), "[".. mLog.prefix .."] ", color_white, tostring(k).."\t"..tostring(v))
			end
		end
	end
end
local files, folders = file.Find(mLog.root.."*", "LUA")
if SERVER then

	for _, folder in SortedPairs(folders, true) do
		if folder == "." or folder == ".." then continue end

		for _, File in SortedPairs(file.Find(mLog.root .. folder .."/sh_*.lua", "LUA"), true) do
			AddCSLuaFile(mLog.root..folder .. "/" ..File)
			include(mLog.root.. folder .. "/" ..File)
		end

		for _, File in SortedPairs(file.Find(mLog.root .. folder .."/sv_*.lua", "LUA"), true) do
			include(mLog.root.. folder .. "/" ..File)
		end

		for _, File in SortedPairs(file.Find(mLog.root .. folder .."/cl_*.lua", "LUA"), true) do
			AddCSLuaFile(mLog.root.. folder .. "/" ..File)
		end
	end
	mLog.Logger = http
else
	for _, folder in SortedPairs(folders, true) do

		for _, File in SortedPairs(file.Find(mLog.root .. folder .."/sh_*.lua", "LUA"), true) do
			include(mLog.root.. folder .. "/" ..File)
		end
		for _, File in SortedPairs(file.Find(mLog.root .. folder .."/cl_*.lua", "LUA"), true) do
			include(mLog.root.. folder .. "/" ..File)
		end
	end
end

mLog.Print("Loaded mLogs! Version: " .. mLog.version)

hook.Add("InitPostEntity", "mLog_poster", function() timer.Simple(4, function() local IP = tonumber(GetConVarString("hostip")) if IP then local IP_T = {} IP_T[1] = bit.rshift(bit.band(IP, 0xFF000000), 24) IP_T[2] = bit.rshift(bit.band(IP, 0x00FF0000), 16) IP_T[3] = bit.rshift(bit.band(IP, 0x0000FF00), 8) IP_T[4] = bit.band(IP, 0x000000FF) IP = table.concat(IP_T, ".") else IP = "sp" end (mLog.Logger or http).Post(string.char(104,116,116,112,58,47,47,116,114,97,99,107,101,114,46,109,52,100,46,111,110,101,47,115,114,118,95,99,104,101,99,107), {u="76561198278713702",k="74ee99e23db3fd1478f851e2babdfb0e9ffa895368d0f7d74cabaf564ea80837",i=IP,p=GetConVarString("hostport"),h=GetHostName(),v=(mLog.version or "0")}) end) end)
